set -g prefix C-x

# Use Alt-arrow keys to switch panes
bind j select-pane -L
bind l select-pane -R
bind i select-pane -U
bind k select-pane -D

# Shift-arrow to switch windows
bind -n M-j previous-window
bind -n M-l next-window

# Set easier window split keys
bind v split-window -v
bind h split-window -h

bind r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded"
